# Generated by Django 4.2.6 on 2023-10-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
