# Generated by Django 4.2.5 on 2023-10-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='titulaciones',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='personastitulaciones',
            unique_together={('persona', 'titulacion', 'tipo')},
        ),
    ]
