# Generated by Django 4.2.2 on 2023-08-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrios',
            options={'managed': False, 'verbose_name': 'Barrio'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'managed': False, 'verbose_name': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='carreras',
            options={'managed': False, 'verbose_name': 'Carrera'},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'managed': False, 'verbose_name': 'Ciudad'},
        ),
        migrations.AlterModelOptions(
            name='facultades',
            options={'managed': False, 'verbose_name': 'Facultad'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'managed': False, 'verbose_name': 'Genero'},
        ),
        migrations.AlterModelOptions(
            name='lugares',
            options={'managed': False, 'verbose_name': 'Lugar'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'managed': False, 'verbose_name': 'Pais'},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': False, 'verbose_name': 'persona'},
        ),
        migrations.AlterModelOptions(
            name='personastitulaciones',
            options={'managed': False, 'verbose_name': 'Persona Titulaciones'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'managed': False, 'verbose_name': 'Provincia'},
        ),
        migrations.AlterModelOptions(
            name='tipospersona',
            options={'managed': False, 'verbose_name': 'Tipo de persona'},
        ),
        migrations.AlterModelOptions(
            name='titulaciones',
            options={'managed': False, 'verbose_name': 'Titulacion'},
        ),
        migrations.AlterModelOptions(
            name='universidades',
            options={'managed': False, 'verbose_name': 'Universidad'},
        ),
    ]
