# Generated by Django 4.2.2 on 2023-08-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ispc', '0002_alter_barrios_options_alter_campus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrios',
            options={'managed': False, 'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'managed': False, 'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
        migrations.AlterModelOptions(
            name='carreras',
            options={'managed': False, 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='ciudades',
            options={'managed': False, 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='facultades',
            options={'managed': False, 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AlterModelOptions(
            name='generos',
            options={'managed': False, 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='lugares',
            options={'managed': False, 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'managed': False, 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': False, 'verbose_name': 'persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='personastitulaciones',
            options={'managed': False, 'verbose_name': 'Persona Titulaciones', 'verbose_name_plural': 'PersonasTitulaciones'},
        ),
        migrations.AlterModelOptions(
            name='provincias',
            options={'managed': False, 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='tipospersona',
            options={'managed': False, 'verbose_name': 'Tipo de persona', 'verbose_name_plural': 'Tipos de persona'},
        ),
        migrations.AlterModelOptions(
            name='titulaciones',
            options={'managed': False, 'verbose_name': 'Titulacion', 'verbose_name_plural': 'Titulaciones'},
        ),
        migrations.AlterModelOptions(
            name='universidades',
            options={'managed': False, 'verbose_name': 'Universidad', 'verbose_name_plural': 'Universidades'},
        ),
    ]
